# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Bug fixed 🛠
      labels:
    - title: New features
      labels:
        - enhancement
    - title: Other Changes
      labels:
        - "*"
