repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
        exclude: '.*\.cif$'
    -   id: end-of-file-fixer
        exclude: '.*\.cif$'
    -   id: trailing-whitespace
        exclude: '.*\.cif$'
    -   id: check-toml
        exclude: '.*\.cif$'
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
    -   id: ruff
        args: [ --fix ]
        exclude: '.*\.cif$'
    -   id: ruff-format
        exclude: '.*\.cif$'
