

[project]
name = "cifkit"
version = "1.0.2"
description = "Python library for high-throughput .cif analysis"
authors = [{name = "Sangjoon Lee", email = "bobleesj@gmail.com"}]
readme = "README.md"
license = {file = "LICENSE"}
keywords = ["cif", "solid-state", "high-throughput", "crystallography"]

dependencies = [
    "gemmi==0.6.6",
    "matplotlib==3.8.3",
    "numpy==1.26.4",
    "pyvista==0.43.9",
    "scipy==1.13.1",
    "setuptools==67.8.0"
]

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
line-length = 79
